# Generated by Django 4.2.16 on 2024-11-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0002_delete_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=100)),
                ("members", models.JSONField()),
                (
                    "game_version",
                    models.CharField(
                        choices=[
                            ("D&D", "D&D"),
                            ("M&M", "Mutants & Masterminds"),
                            ("PF", "Pathfinder"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
