# Generated by Django 4.2.16 on 2024-11-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groups",
            name="group_description",
            field=models.TextField(default="image"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="groups",
            name="group_pic",
            field=models.ImageField(default="image", upload_to=""),
            preserve_default=False,
        ),
    ]
