# Generated by Django 4.2.16 on 2024-11-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_groups_group_description_groups_group_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        choices=[("fake4091", "fake4091"), ("Test_User", "Test_User")],
                        max_length=150,
                    ),
                ),
                ("notification", models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name="groups",
            name="group_pic",
            field=models.ImageField(default="app/static/test.png", upload_to=""),
        ),
    ]
