# Generated by Django 4.2.16 on 2024-11-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_notifications_alter_groups_group_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="notification",
            field=models.JSONField(default=[]),
        ),
    ]
