# Generated by Django 4.2.16 on 2024-11-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_notifications_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="notification",
            field=models.JSONField(default=list),
        ),
    ]
