# Generated by Django 4.2.16 on 2024-11-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_groups_group_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groups",
            name="group_name",
            field=models.CharField(max_length=100),
        ),
    ]
